name: Build and Release

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.VER }}
      cver: ${{ steps.getversion.outputs.CVER }}
    steps:
      -
        name: Get version
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/minetaro12/cloudflared-mipsle/releases/latest | jq -r '.tag_name'`
          echo "::set-output name=VER::$ver"
          echo "::set-output name=CVER::$cver"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{needs.check.outputs.ver != needs.check.outputs.cver}}
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.8
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build
        run: |
          git clone https://github.com/cloudflare/cloudflared -b ${{needs.check.outputs.ver}} ../src
          cd ../src
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat make cloudflared
          mv cloudflared cloudflared-linux-mipsle
      - 
        name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{needs.check.outputs.ver}}
          prerelease: false
          files: |
              ../src/cloudflared-linux-mipsle

